project:
  type: website
  output-dir: docs    # ← GitHub Pages will serve from docs/

site-lib-dir: docs/site-libs   # ← here
website:
  title: "My Forecaster Explorer"
  navbar:
    right:
      - text: Home
        href: index.html

        