project:
  type: website
  output-dir: docs    # ← GitHub Pages will serve from docs/
  render:
    # render this notebook as docs/index.html
    - src/Forcaster_Explorer.ipynb:
        output-file: index.html

site-lib-dir: docs/site-libs   # ← here
website:
  title: "Weekly ConvoKit Updates"
  navbar:
    right:
      - text: Home
        href: index.html

        