project:
  type: website
  output-dir: docs    # ← GitHub Pages will serve from docs/
  render:
    - "!CRAFT/"
    - "!convokit_notebooks/"
    - "src/"

site-lib-dir: docs/site-libs   # ← here
website:
  title: "Weekly ConvoKit Updates"
  navbar:
    right:
      - text: Home
        href: index.html

        