project:
  type: website
  output-dir: docs    # ← GitHub Pages will serve from docs/
  render:
    - "!CRAFT/"
    - "!convokit_notebooks/"
    - "src/Forcaster_Explorer.ipynb"
    - "!src/CRAFT_Corpus_Explorer.ipynb"
    - "!src/debugger.ipynb"
    - "!src/corpus_converter.ipynb"
    - index.qmd

site-lib-dir: docs/site-libs   # ← here
website:
  title: "Weekly ConvoKit Updates"
  navbar:
    right:
      - text: Home
        href: index.html

        