@startuml
skinparam linetype ortho
skinparam dpi 300
left to right direction
!define COMMENT(x) <b><color:RoyalBlue>x</color></b>
' Core Tuple structure


package "Context Tuple" {
    ' Components of the context tuple
  
     object Context {
    +utterances : List<Utterance>
        --
        COMMENT(past + current)
    }

    object CurrentUtterance {
    +utterance : Utterance
    -- 
    COMMENT(prediciton)
    }

    package "Training Phase Only"#00298cb3 {
        object FutureContext {
        +utterances : List<Utterance>
        --
        COMMENT(future) 
        }   

    }

}

' --- Hidden links to enforce vertical order ---
    Context -[hidden]-> CurrentUtterance
    CurrentUtterance -[hidden]-> FutureContext


@enduml
