@startuml
skinparam linetype ortho
skinparam dpi 300
!theme carbon-gray
' Core Classes

class Corpus{
      + meta 
}
class Speaker {
         + meta 
}
class Utterance{
   + meta 
}
class Conversation{
    + meta 
}

Corpus *-- Conversation
Corpus *-- Utterance
Conversation o-- Utterance
Corpus *-- Speaker
Utterance <-- Utterance : \nreplies to
@enduml
