@startuml
skinparam linetype ortho
skinparam dpi 300
!theme sunlust

' Core Classes
class Corpus {
    + meta
}

class Speaker {
    + meta
    + vector
}

class Utterance {
    + meta
    + vector
}

class Conversation {
    + meta
    + vector
}

' Relationships
Corpus *-- Conversation
Corpus *-- Utterance
Corpus *-- Speaker

Conversation o-- Utterance
Utterance <-- Utterance : \nreplies to

@enduml
